### ISSUE TITLE
Error saving Twitter link

### ISSUE THREAD

**Issue by jasoslav** [justinklemm/crisp-persona#20]
First - thank you for nice theme. :)

When I am customizing theme, and putting twitter link e.g."http://twitter.com/samuelzubo‎" on main page is publicized the link:
"https://twitter.com/samuelzubo%E2%80%8E", which throws an error on twitter page.

**Comment by justinklemm** [comment]
@jasoslav - It looks like you have (invisible) irregular characters at the end of your link. I don't think the theme is adding these. Even when I click the link above (in you e.g.), I get the error page with characters at the end of it. Try typing in the Twitter URL from scratch. Don't copy/paste it.
